import { useState } from "react";
import { MenuCloseIcon } from "../../../common/header/Header.styles";
import {
  Center,
  Check,
  CheckBox,
  CheckBoxText,
  CheckBoxWrapper,
  Container,
  ContinueBtn,
  Description,
  InnerWrapper,
  Left,
  ModalCloseBtnWrapper,
  ModalNavWrapper,
  ModalWrapper,
  OuterWrapper,
  Overlay,
  Right,
  Title,
} from "./About.styles";
import { useDispatch, useSelector } from "react-redux";
import { openModal } from "../../../../store/reducers/modals";
import { Modals } from "../types";
import MainLogo from "../../../common/mainLogo/MainLogo";
import { RootState } from "../../../../store";

type Props = {
  isOpen: boolean;
};

const About = (props: Props) => {
  const dispatch = useDispatch();
  const modalState = useSelector((state: RootState) => state.modal.open);
  const [isChecked, setIsChecked] = useState<boolean>(false);

  const handleClickContinue = () => {
    if (!isChecked) {
      alert("checkbox required");
      return;
    }
    dispatch(openModal(Modals.NONE));
  };

  return (
    <ModalWrapper isOpen={props.isOpen}>
      <Overlay />
      <Container>
        <ModalNavWrapper>
          <Left></Left>
          <Center>
            <MainLogo tabIndex={modalState === Modals.ABOUT ? 0 : -1} />
          </Center>
          <Right>
            <ModalCloseBtnWrapper
              tabIndex={0}
              onClick={() => dispatch(openModal(Modals.NONE))}
              onKeyDown={(e) =>
                e.key === "Enter" ? dispatch(openModal(Modals.NONE)) : ""
              }
            >
              <MenuCloseIcon src="/header/close_btn.svg" />
            </ModalCloseBtnWrapper>
          </Right>
        </ModalNavWrapper>
        <OuterWrapper>
          <InnerWrapper>
            <Title>About the platform</Title>
            <Description>
              All of the characters here are not real. Everything you see and
              hear is entirely generated by Artificial Intelligence machines.
              The opinions and beliefs expressed do not represent anyone. They
              are hallucinations of a bunch of 1s and 0s inside of a magic
              computer.
              <br />
              <br />
              The creators of this platform have the best intentions with this
              project, and deeply admire each and every character on the site.
              You might even say they are our Heroes. In fact, you can say that.
            </Description>
            <CheckBoxWrapper>
              <CheckBox
                tabIndex={0}
                onClick={() => setIsChecked((prev) => !prev)}
                onKeyDown={(e) =>
                  e.key === "Enter" ? setIsChecked((prev) => !prev) : ""
                }
              >
                <Check isChecked={isChecked} src="/check.svg" />
              </CheckBox>
              <CheckBoxText>I have read the above statement</CheckBoxText>
            </CheckBoxWrapper>
            <ContinueBtn
              tabIndex={0}
              onClick={() => handleClickContinue()}
              onKeyDown={(e) =>
                e.key === "Enter" ? handleClickContinue() : ""
              }
            >
              continue
            </ContinueBtn>
          </InnerWrapper>
        </OuterWrapper>
      </Container>
    </ModalWrapper>
  );
};

export default About;
