export const individualsData = [
  {
    fullName: "dr. martin luther king jr.",
    title: "political activist",
    imgUrl: "/ind/photos/l_king.png",
    substrateUrl: "/ind/sub/1.png",
  },
  {
    fullName: "Steve Jobs",
    title: "Apple Computer Founder",
    imgUrl: "/ind/photos/s_jobs.png",
    substrateUrl: "/ind/sub/2.png",
  },
  {
    fullName: "elon musk",
    title: "space nerd",
    imgUrl: "/ind/photos/e_musk.png",
    substrateUrl: "/ind/sub/3.png",
  },
  {
    fullName: "albert einstein",
    title: "genius",
    imgUrl: "/ind/photos/a_einstein.png",
    substrateUrl: "/ind/sub/4.png",
  },
  {
    fullName: "mother teresa",
    title: "philanthropist",
    imgUrl: "/ind/photos/m_teresa.png",
    substrateUrl: "/ind/sub/5.png",
  },
  {
    fullName: "jesus christ",
    title: "lord & savior",
    imgUrl: "/ind/photos/j_christ.png",
    substrateUrl: "/ind/sub/6.png",
  },
  {
    fullName: "leonardo da vinci",
    title: "artist",
    imgUrl: "/ind/photos/l_da_vinci.png",
    substrateUrl: "/ind/sub/7.png",
  },
  {
    fullName: "queen elizabeth",
    title: "queen of england",
    imgUrl: "/ind/photos/q_elizabeth.png",
    substrateUrl: "/ind/sub/8.png",
  },
  {
    fullName: "william shakespeare",
    title: "author",
    imgUrl: "/ind/photos/w_shakespeare.png",
    substrateUrl: "/ind/sub/9.png",
  },
  {
    fullName: "nelson mandela",
    title: "philanthropist",
    imgUrl: "/ind/photos/n_mandela.png",
    substrateUrl: "/ind/sub/10.png",
  },
  {
    fullName: "betsy ross",
    title: "american history",
    imgUrl: "/ind/photos/b_ross.png",
    substrateUrl: "/ind/sub/11.png",
  },
  {
    fullName: "gandhi",
    title: "philanthropist",
    imgUrl: "/ind/photos/gandhi.png",
    substrateUrl: "/ind/sub/12.png",
  },
  {
    fullName: "abraham lincoln",
    title: "american president",
    imgUrl: "/ind/photos/a_lincoln.png",
    substrateUrl: "/ind/sub/13.png",
  },
  {
    fullName: "ron swanson",
    title: "tv goofy guy",
    imgUrl: "/ind/photos/r_swanson.png",
    substrateUrl: "/ind/sub/14.png",
  },
];
